version: 0.2

phases:
  install:
    commands:
      - pip3 install --upgrade awscli
      - npm install
      - npm run build
      - aws s3 sync --delete dist/ s3://dansoup.co.uk main --acl public-read