version: 0.2

phases:
  install:
      commands:
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - sudo ./aws/install
          - npm install
          - LIVE_PUBLIC_PATH=$PUBLIC_PATH
          - npm run live
          - aws s3 sync --delete dist/ $MAIN_BUCKET/main