version: 0.2

env:
  variables:
    BS_FOLDER: "apps"
    BS_URL: "test"

phases:
  install:
      commands:
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - sudo ./aws/install
          - npm install
          - LIVE_PUBLIC_PATH=$PUBLIC_PATH/$BS_FOLDER/$BS_URL
          - npm run live
          - aws s3 sync --delete dist/ $APP_BUCKET/$BS_FOLDER/$BS_URL